name: Build Documents
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Typst
        uses: lvignoli/typst-action@v0
        with:
          source_file: |
            Typst/template/main.typ
            Typst/example/Lab-Report-Typ.typ
      - name: LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: LaTeX/Lab-Report-TeX.tex
          latexmk_shell_escape: true
        env:
          TEXINPUTS: "./LaTeX/:"
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: |
            Typst/template/main.pdf
            Typst/template/Lab-Report-Typ.pdf
            LaTeX/Lab-Report-TeX.pdf
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: |
            Typst/template/main.pdf
            Typst/example/Lab-Report-Typ.pdf
            LaTeX/Lab-Report-TeX.pdf
            Lab-Report-TeX.pdf
