name: Build Typst Documents
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Typst
      uses: lvignoli/typst-action@v0
      with:
        source_file: |
          Typst/template/main.typ
          Typst/example/Lab-Report.typ
    - name: Upload PDF file
      uses: actions/upload-artifact@v3
      with:
        name: PDFs
        path: |
          Typst/template/main.pdf
          Lab-Report.pdf
    - name: Get current date
      id: date
      run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Typst/template/main.pdf
          Lab-Report.pdf